### ISSUE TITLE
Support for ` "curve-style": "taxi"`  for edges

### ISSUE THREAD

**Issue by vivekvs1** [plotly/dash-cytoscape#44]
Hi, I could not find a way to use  ` "curve-style": "taxi"` for the edges. Is there a way to do so? I was unable to find where in `react-cytoscape` I should be looking if its present.

**Comment by xhlulu** [comment]
If it's not available by default in Cytoscape.js, then you likely won't be able to use it.

**Comment by vivekvs1** [comment]
I believe that its a part of the Cytoscape package isn't it?

**Comment by xhlulu** [comment]
Yes. I looked at the issues on Cytoscape.js, and [found this](https://github.com/cytoscape/cytoscape.js/issues/2306). It was added recently (version 3.5.0).

I would recommend you to comment on [this PR](https://github.com/plotly/react-cytoscapejs/pull/15) if you would like to see react-cytoscape.js to be updated. Once it's done, please reopen this issue and I'll update `dash-cytoscape` to match the new react version

**Comment by vivekvs1** [comment]
Oh wow- thank you :). 

By the way- this package is so cool. With all the things one can do easily.

**Comment by xhlulu** [comment]
Thanks! I'll close this until react-cytoscapejs is updated!

**Comment by maxkfranz** [comment]
@xhlulu If you want the Dash component to use a specific version of Cytoscape to use particular Cytoscape features, then the `package.json` file for `dash-cytoscape` should specify `cytoscape` as a `dependency` with the desired version.

The default behaviour of npm is a bit weird.  If a dependency specifies version `foo@^1.2.3`, npm will install 1.2.3 even if newer versions exist that match the semver range.  The only way to get a newer version by default is for a different dependency to specify a higher compatible version or for the app itself to specify one.

When you do `npm install cytoscape@3.5.0` within `dash-cytoscape`, for example, you will make npm find the version number that satisfies both `dash-cytoscape` and `react-cytoscapejs`.  Because `dash-cytoscape` would specify a newer version that is also compatible with the semver range for `react-cytoscapejs`, the version that `dash-cytoscape` specifies would be used.

An upgrade within `react-cytoscapejs` could be considered a breaking change:  A developer whose app works with a previous compatible version of Cytoscape, say 3.4, may want to be conservative and only get patch versions of 3.4.x.  If `react-cytoscapejs` specifies a new version like `3.5.0` in its `package.json` file, then the dev is forced to use the newer version of Cytoscape.  It takes control away from devs.

Because the Dash component is more high-level and user-facing -- it may rely on specific features, whereas the React component is more general -- I think it would be more appropriate for the Dash component to specify a newer version of Cytoscape.js.

If you run into difficulties with this approach or if you have concerns about it, let me know.

**Comment by walter-cavinaw** [comment]
@maxkfranz are you saying that the fix for this is to add a higher cytoscape version to the package.json file of dash-cytoscape? if i edit the package.json file on my machine should that have the same effect? I am trying to get this working but changing the package file didn't seem to work.
